DebugMode: false

ModifySkills: true
ModifyJobs: true

# Taming is not included
Skills:
  Acrobatics:
    Jobs:
      - Explorer
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Alchemy:
    Jobs:
      - Brewer
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Archery:
    Jobs:
      - Hunter
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Axes:
    Jobs:
      - Hunter
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Excavation:
    Jobs:
      - Digger
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Fishing:
    Jobs:
      - Fisherman
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Herbalism:
    Jobs:
      - Farmer
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Mining:
    Jobs:
      - Miner
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Repair:
    Jobs:
      - Blacksmith
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Swords:
    Jobs:
      - Hunter
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Unarmed:
    Jobs:
      - Hunter
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10
  Woodcutting:
    Jobs:
      - Woodcutter
    TargetType: Highest
    LevelMin: 0
    LevelMax: 100
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 10

Jobs:
  Woodcutter:
    Skills:
      - Woodcutting
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Miner:
    Skills:
      - Mining
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Builder:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Digger:
    Skills:
      - Excavation
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Farmer:
    Skills:
      - Herbalism
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Hunter:
    Skills:
      - Swords
      - Axes
      - Archery
      - Unarmed
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Explorer:
    Skills:
      - Acrobatics
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Crafter:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Fisherman:
    Skills:
      - Fishing
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Weaponsmith:
    Skills:
      - Repair
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Brewer:
    Skills:
      - Alchemy
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Enchanter:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100