Jobs:
  Woodcutter:
    Skills:
      - Woodcutting
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Miner:
    Skills:
      - Mining
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Builder:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Digger:
    Skills:
      - Excavation
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Farmer:
    Skills:
      - Herbalism
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Hunter:
    Skills:
      - Swords
      - Axes
      - Archery
      - Unarmed
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Explorer:
    Skills:
      - Acrobatics
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Crafter:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Fisherman:
    Skills:
      - Fishing
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Weaponsmith:
    Skills:
      - Repair
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Brewer:
    Skills:
      - Alchemy
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100
  Enchanter:
    Skills: []
    TargetType: Highest
    SkillMin: 0
    SkillMax: 1000
    MultMin: 0.5
    MultMax: 2.0
    EnforceMinimum: 100